# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
import webbrowser

from config.definitions import img_dir, txt_dir
from src.app.ui.AboutForm.AboutForm import UiAboutForm
from PyQt5 import QtCore, QtGui, QtWidgets, QtSvg


def redirect_to_github_repo():
    webbrowser.open('https://github.com/greg-ynx/Geopedia-regions-countries-capital_cities')


class MainWindow(object):

    def __init__(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(900, 640)
        main_window.setMinimumSize(QtCore.QSize(900, 640))
        main_window.setBaseSize(QtCore.QSize(900, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(img_dir, "geopedia_logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)

        self.help_geopedia_widget = QtWidgets.QWidget()
        self.help_geopedia_form = UiAboutForm(self.help_geopedia_widget,
                                              "Geopedia help",
                                              os.path.join(img_dir, 'QuestionMark.png'),
                                              os.path.join(txt_dir, 'help_geopedia.txt'))

        self.about_greg_ynx_widget = QtWidgets.QWidget()
        self.about_greg_ynx_form = UiAboutForm(self.about_greg_ynx_widget,
                                               "About greg-ynx",
                                               os.path.join(img_dir, 'ynx_logo_800px.png'),
                                               os.path.join(txt_dir, 'about_greg-ynx.txt'))

        self.main_window_centralWidget = QtWidgets.QWidget(main_window)
        self.main_window_centralWidget.setObjectName("main_window_centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_window_centralWidget)
        self.gridLayout.setObjectName("gridLayout")

        self.tab_widget = QtWidgets.QTabWidget(self.main_window_centralWidget)
        self.tab_widget.setObjectName("tab_widget")

        self.tab_location_browser = QtWidgets.QWidget()
        self.tab_location_browser.setObjectName("tab_location_browser")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_location_browser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.capital_city_comboBox = QtWidgets.QComboBox(self.tab_location_browser)
        self.capital_city_comboBox.setObjectName("capital_city_comboBox")
        self.gridLayout_2.addWidget(self.capital_city_comboBox, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.capital_city_label = QtWidgets.QLabel(self.tab_location_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capital_city_label.sizePolicy().hasHeightForWidth())
        self.capital_city_label.setSizePolicy(sizePolicy)
        self.capital_city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.capital_city_label.setObjectName("capital_city_label")
        self.gridLayout_2.addWidget(self.capital_city_label, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.country_comboBox = QtWidgets.QComboBox(self.tab_location_browser)
        self.country_comboBox.setObjectName("country_comboBox")
        self.gridLayout_2.addWidget(self.country_comboBox, 2, 1, 1, 1)
        self.region_label = QtWidgets.QLabel(self.tab_location_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.region_label.sizePolicy().hasHeightForWidth())
        self.region_label.setSizePolicy(sizePolicy)
        self.region_label.setAlignment(QtCore.Qt.AlignCenter)
        self.region_label.setObjectName("region_label")
        self.gridLayout_2.addWidget(self.region_label, 1, 0, 1, 1)
        self.country_label = QtWidgets.QLabel(self.tab_location_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_label.sizePolicy().hasHeightForWidth())
        self.country_label.setSizePolicy(sizePolicy)
        self.country_label.setAlignment(QtCore.Qt.AlignCenter)
        self.country_label.setObjectName("country_label")
        self.gridLayout_2.addWidget(self.country_label, 1, 1, 1, 1)
        self.region_comboBox = QtWidgets.QComboBox(self.tab_location_browser)
        self.region_comboBox.setObjectName("region_comboBox")
        self.gridLayout_2.addWidget(self.region_comboBox, 2, 0, 1, 1)
        self.svg_widget = QtSvg.QSvgWidget(self.tab_location_browser)
        self.svg_widget.setObjectName("svg_widget")
        self.gridLayout_2.addWidget(self.svg_widget, 4, 0, 1, 3)
        self.tab_widget.addTab(self.tab_location_browser, "")
        self.tab_countries_list = QtWidgets.QWidget()
        self.tab_countries_list.setObjectName("tab_countries_list")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_countries_list)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.countries_list_scrollArea = QtWidgets.QScrollArea(self.tab_countries_list)
        self.countries_list_scrollArea.setWidgetResizable(True)
        self.countries_list_scrollArea.setObjectName("countries_list_scrollArea")
        self.countries_list_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.countries_list_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 856, 504))
        self.countries_list_scrollAreaWidgetContents.setObjectName("countries_list_scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.countries_list_scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.countries_list_tableWidget = QtWidgets.QTableWidget(self.countries_list_scrollAreaWidgetContents)
        self.countries_list_tableWidget.setObjectName("countries_list_tableWidget")
        self.countries_list_tableWidget.setColumnCount(0)
        self.countries_list_tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.countries_list_tableWidget, 0, 0, 1, 1)
        self.countries_list_scrollArea.setWidget(self.countries_list_scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.countries_list_scrollArea, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_countries_list, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)
        self.bottom_horizontalLayout = QtWidgets.QHBoxLayout()
        self.bottom_horizontalLayout.setObjectName("bottom_horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_horizontalLayout.addItem(spacerItem2)
        self.save_button = QtWidgets.QPushButton(self.main_window_centralWidget)
        self.save_button.setObjectName("save_button")
        self.bottom_horizontalLayout.addWidget(self.save_button)
        self.gridLayout.addLayout(self.bottom_horizontalLayout, 1, 0, 1, 1)
        main_window.setCentralWidget(self.main_window_centralWidget)

        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        main_window.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.action_Help_Geopedia = QtWidgets.QAction(main_window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(img_dir, "QuestionMark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help_Geopedia.setIcon(icon1)
        self.action_Help_Geopedia.setObjectName("action_Help_Geopedia")
        self.action_Help_Geopedia.triggered.connect(self.help_geopedia_widget.show)

        self.action_About_greg_ynx = QtWidgets.QAction(main_window)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(img_dir, "ynx_logo_800px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About_greg_ynx.setIcon(icon2)
        self.action_About_greg_ynx.setObjectName("action_About_greg_ynx")
        self.action_About_greg_ynx.triggered.connect(self.about_greg_ynx_widget.show)

        self.action_Join_us_on_GitHub = QtWidgets.QAction(main_window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(img_dir, "GitHub.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Join_us_on_GitHub.setIcon(icon3)
        self.action_Join_us_on_GitHub.setObjectName("action_Join_us_on_GitHub")
        self.action_Join_us_on_GitHub.triggered.connect(redirect_to_github_repo)

        self.menuHelp.addAction(self.action_Help_Geopedia)
        self.menuHelp.addAction(self.action_About_greg_ynx)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_Join_us_on_GitHub)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Geopedia"))
        self.capital_city_label.setText(_translate("MainWindow", "Capital city"))
        self.region_label.setText(_translate("MainWindow", "Region"))
        self.country_label.setText(_translate("MainWindow", "Country"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_location_browser),
                                   _translate("MainWindow", "Location browser"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_countries_list),
                                   _translate("MainWindow", "Countries list"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_Help_Geopedia.setText(_translate("MainWindow", "Geopedia help"))
        self.action_About_greg_ynx.setText(_translate("MainWindow", "About greg-ynx"))
        self.action_Join_us_on_GitHub.setText(_translate("MainWindow", "Join us on GitHub!"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = MainWindow(window)
    window.show()
    sys.exit(app.exec_())
